# Generated by Django 6.0.4 on 2026-04-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=9)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField()),
                ('description', models.TextField(max_length=200)),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
